#!/bin/sh -e

if [ "$1" = "update" ]; then
	./sw-names | xargs -i echo ./dell-switch.pl {} "'show system'" | parallel
fi

(
echo "All fans breakdown by status:"
grep Fan log/*system* | cut -d: -f3 | sort | uniq -c
echo
echo "Failing fans:"
grep -B 15 'NOT' log/*system* | egrep '(NOT|Description|Type)' | grep -v -- '-Type: *Ethernet Switch' | sed -e 's/^[^_]*_//' -e 's/_[^-:]*[-:]/ /'
) | tee /dev/shm/fans
git -C /dev/shm add fans
git -C /dev/shm commit -m fans
