#!/bin/bash
cat dell | while read line
do
	snmpwalk -v 2c -c XXXXXXXXXXXXXXXXXXX $line 1.3.6.1.2.1.17.4.3.1.2 | sed 's/iso.3.6.1.2.1.17.4.3.1.2./ /g' | awk '{print $1" .g"$4}' | awk -v sw="$line" -F '.' '{ printf "%02X:%02X:%02X:%02X:%02X:%02X,%s,%s\n", $1, $2, $3, $4, $5, $6, $7, sw }'
done
